# Generated by Django 5.0.3 on 2024-03-20 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message="Содержание поля 'username' не соответствует паттерну '^[\\w.@+-]+\\z'", regex='^[\\w.@+-]+\\Z')]),
        ),
    ]
